### ISSUE TITLE
Need to fix css for social button used in Footer widgets(Footer Sidebar)

### ISSUE THREAD

**Issue by bhrugesh96** [tomusborne/generatepress#398] opened 2022-06-13 09:38 UTC
### Description
When I adding social icon Gutenberg widget in any area of footer. There is margin spacing issue for last li Element. So we need to add margin support for last element too.

### Steps to reproduce
1. Go to Appearance -> Widgets.
2. Add Social Icons Widget in any footer Area. ( Footer Widget )
3. Add 7 to 8 Social icons.
4. Check last li element - that last element not align to others.

#### Actual behavior
Check Attached Picture - https://prnt.sc/3PGMveXD361A

#### Expected behavior
Check screenshot - https://prnt.sc/fp4iRcNcAh60

---

**Comment by fernandoazarcon2** [comment] 2023-06-28 04:04
+1 https://generate.support/topic/social-icons-misaligned-in-widget/#post-22087

**Comment by diggeddy** [comment] 2023-10-19 10:46
This is not specifically related to the social icons.
The issue is this CSS from the theme:

```
.footer-widgets .widget :last-child, .sidebar .widget :last-child {
    margin-bottom: 0;
}
```

Which is necessary to remove unnecessary spacing after last child in a widget area.
Modifying this CSS to eliminate specific issue is not a viable option.

Ideally the block itself should consider margins in the block CSS.
And that can be achieved by adding this CSS:

```
aside .wp-block-social-links .wp-block-social-link {
    margin-bottom: 0;
} 
```

Closing this as nofix in the theme.

**Closed by diggeddy** 2023-10-19 10:46 UTC
Labels: nofix
