### ISSUE TITLE
In Preium Feature Elements And Hook editing window can not appeiar

### ISSUE THREAD

**Issue by Ptnaman** [tomusborne/generatepress#657] opened 2024-12-21 12:44 UTC
### Description
When i Create Related post on Element > Block-hook it will completed but I next time it open it shows blank error
![image](https://github.com/user-attachments/assets/e14404fb-ce0e-4c6a-a6e0-efd3cb035ce0)
![image](https://github.com/user-attachments/assets/96baa6ea-3324-4dfc-877b-30171f326adc)
![image](https://github.com/user-attachments/assets/698536bb-e5ed-447b-a386-f3f9d84e5e76)

I also use premium genratepress theme no null,no crack original theme

Sometime it shows same problem in hook and block also

please solve my problem as soon as possible

**Comment by diggeddy** [comment] 2024-12-21 16:08
This is not a bug. And GitHub is not the place for racing support topics.
Closing this issue
Please raised a support topic from your account at generatepress.com

**Closed by diggeddy** 2024-12-21 16:08 UTC
Labels: bug, triage
